#pragma once

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_WS GPIO_NUM_10
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_9
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_11
#define AUDIO_CODEC_PA_PIN GPIO_NUM_53
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_7
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_8

#define DISPLAY_WIDTH 720
#define DISPLAY_HEIGHT 1280
#define DISPLAY_CONTROL_I2C_ADDRESS 0x45
#define DISPLAY_DSI_LANE_BITRATE_MBPS 1000
#define DISPLAY_PHY_LDO_CHANNEL 3
#define DISPLAY_PHY_LDO_MV 2500
