// Generated by scripts/generate_counter_ui.py.
#pragma once
#include <lvgl.h>
LV_FONT_DECLARE(counter_font_16);
LV_FONT_DECLARE(counter_font_18);
LV_FONT_DECLARE(counter_font_20);
LV_FONT_DECLARE(counter_font_24);
LV_FONT_DECLARE(counter_font_28);
LV_FONT_DECLARE(counter_font_32);
LV_FONT_DECLARE(counter_font_44);
LV_FONT_DECLARE(counter_font_76);
struct CounterUiItem {int x,y,w,h; uint32_t color,ink; int radius,action; const char* text; const lv_font_t* font; lv_text_align_t align;};
static const CounterUiItem kCounterPage0[]={
{32,31,8,32,0xe4c58a,0xf2f0e8,3,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{56,22,600,0,0x101716,0xf2f0e8,0,-1,"星豚 · 智慧柜台",&counter_font_28,LV_TEXT_ALIGN_LEFT},
{1020,30,228,0,0x101716,0x94a49b,0,-1,"柜台 01",&counter_font_20,LV_TEXT_ALIGN_RIGHT},
{56,91,1000,0,0x101716,0x94a49b,0,-1,"透明计价  安心选购",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{32,137,1216,1,0x33403a,0xf2f0e8,0,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{32,654,1216,1,0x33403a,0xf2f0e8,0,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{44,676,700,0,0x101716,0x94a49b,0,-1,"录音未开启",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{32,158,640,402,0x192320,0xf2f0e8,18,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{60,180,310,0,0x101716,0xf2f0e8,0,-1,"今日金价",&counter_font_28,LV_TEXT_ALIGN_LEFT},
{490,188,154,0,0x101716,0xe4c58a,0,-1,"演示报价",&counter_font_18,LV_TEXT_ALIGN_RIGHT},
{60,243,300,0,0x101716,0xe4c58a,0,-1,"足金 999",&counter_font_24,LV_TEXT_ALIGN_LEFT},
{55,275,500,0,0x101716,0xe4c58a,0,-1,"¥898.00",&counter_font_76,LV_TEXT_ALIGN_LEFT},
{545,337,100,0,0x101716,0x94a49b,0,-1,"元/克",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{60,404,584,1,0x33403a,0xf2f0e8,0,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{60,423,250,0,0x101716,0x94a49b,0,-1,"回收参考",&counter_font_18,LV_TEXT_ALIGN_LEFT},
{60,454,280,0,0x101716,0xf2f0e8,0,-1,"¥826.00",&counter_font_32,LV_TEXT_ALIGN_LEFT},
{328,431,1,65,0x33403a,0xf2f0e8,0,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{359,423,275,0,0x101716,0x94a49b,0,-1,"铂金 Pt950",&counter_font_18,LV_TEXT_ALIGN_LEFT},
{359,454,280,0,0x101716,0xf2f0e8,0,-1,"¥368.00",&counter_font_32,LV_TEXT_ALIGN_LEFT},
{60,522,580,0,0x101716,0x94a49b,0,-1,"价格为演示，不作为成交依据",&counter_font_16,LV_TEXT_ALIGN_LEFT},
{32,577,640,58,0x202d25,0xf2f0e8,12,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{55,588,590,0,0x101716,0xe4c58a,0,-1,"每一克有依据，每一项都清晰。",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{696,158,552,477,0x192320,0xf2f0e8,18,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{724,180,285,0,0x101716,0xf2f0e8,0,-1,"本次计价",&counter_font_28,LV_TEXT_ALIGN_LEFT},
{1060,187,160,0,0x101716,0x94a49b,0,-1,"示例商品",&counter_font_18,LV_TEXT_ALIGN_RIGHT},
{724,235,480,0,0x101716,0xf2f0e8,0,-1,"足金素圈手镯",&counter_font_24,LV_TEXT_ALIGN_LEFT},
{724,294,260,0,0x101716,0x94a49b,0,-1,"商品克重",&counter_font_18,LV_TEXT_ALIGN_LEFT},
{984,283,236,0,0x101716,0xf2f0e8,0,-1,"12.680 g",&counter_font_28,LV_TEXT_ALIGN_RIGHT},
{724,340,270,0,0x101716,0x94a49b,0,-1,"金料金额",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{984,336,236,0,0x101716,0xf2f0e8,0,-1,"¥11,386.64",&counter_font_24,LV_TEXT_ALIGN_RIGHT},
{724,385,270,0,0x101716,0x94a49b,0,-1,"工费 · ¥35/克",&counter_font_20,LV_TEXT_ALIGN_LEFT},
{984,381,236,0,0x101716,0xf2f0e8,0,-1,"¥443.80",&counter_font_24,LV_TEXT_ALIGN_RIGHT},
{724,437,496,1,0x33403a,0xf2f0e8,0,-1,nullptr,nullptr,LV_TEXT_ALIGN_LEFT},
{724,454,240,0,0x101716,0x94a49b,0,-1,"预计合计",&counter_font_18,LV_TEXT_ALIGN_LEFT},
{719,478,510,0,0x101716,0xe4c58a,0,-1,"¥11,830.44",&counter_font_44,LV_TEXT_ALIGN_LEFT},
{724,566,496,0,0x101716,0x94a49b,0,-1,"示例计价 · 以门店实际报价为准",&counter_font_20,LV_TEXT_ALIGN_LEFT},
};
struct CounterUiPage {const CounterUiItem* items; size_t count;};
static const CounterUiPage kCounterPages[]={
{kCounterPage0,sizeof(kCounterPage0)/sizeof(kCounterPage0[0])}
};
